version: '3'
services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel_net
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_net
networks:
  laravel_net:
    driver: bridge